#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonParser
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BonDB")]
	public partial class BonDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BonDataContext() : 
				base(global::BonParser.Properties.Settings.Default.BonDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BonDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BonDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertFeature")]
		public int InsertFeature([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> lunch, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> saladBar, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> vegetarian, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> disabled, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> disabledWc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> pizzas, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> weekends, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> fastFood, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> studentBenefits, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> delivery, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] ref System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lunch, saladBar, vegetarian, disabled, disabledWc, pizzas, weekends, fastFood, studentBenefits, delivery, iD);
			iD = ((System.Nullable<int>)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertMenu")]
		public int InsertMenu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string soup, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string mainCourse, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string salad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string dessert, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="R_ID", DbType="Int")] System.Nullable<int> r_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] ref System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), soup, mainCourse, salad, dessert, r_ID, iD);
			iD = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOpening")]
		public int InsertOpening([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> weekStart, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> weekEnd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> saturdayStart, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> saturdayEnd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> sundayStart, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> sundayEnd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] ref System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), weekStart, weekEnd, saturdayStart, saturdayEnd, sundayStart, sundayEnd, iD);
			iD = ((System.Nullable<int>)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TruncateAll")]
		public int TruncateAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_GetRestaurantsInRadius", IsComposable=true)]
		public IQueryable<fn_GetRestaurantsInRadiusResult> fn_GetRestaurantsInRadius([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(9,6)")] System.Nullable<decimal> x, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(9,6)")] System.Nullable<decimal> y, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,3)")] System.Nullable<decimal> radius)
		{
			return this.CreateMethodCallQuery<fn_GetRestaurantsInRadiusResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), x, y, radius);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertRestaurant")]
		public int InsertRestaurant([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(15)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(4,2)")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,14)")] System.Nullable<decimal> coordinateX, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,14)")] System.Nullable<decimal> coordinateY, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> updatedOn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> openingID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> featureID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string menus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, address, phone, price, coordinateX, coordinateY, updatedOn, openingID, featureID, menus);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class fn_GetRestaurantsInRadiusResult
	{
		
		private string _R_Name;
		
		private string _R_Address;
		
		private string _R_Phone;
		
		private System.Nullable<decimal> _R_Price;
		
		private decimal _R_CoordinateX;
		
		private decimal _R_CoordinateY;
		
		private System.DateTime _R_UpdatedOn;
		
		private System.Nullable<System.TimeSpan> _O_WeekStart;
		
		private System.Nullable<System.TimeSpan> _O_WeekEnd;
		
		private System.Nullable<System.TimeSpan> _O_SaturdayStart;
		
		private System.Nullable<System.TimeSpan> _O_SaturdayEnd;
		
		private System.Nullable<System.TimeSpan> _O_SundayStart;
		
		private System.Nullable<System.TimeSpan> _O_SundayEnd;
		
		private string _M_Soup;
		
		private string _M_MainCourse;
		
		private string _M_Salad;
		
		private string _M_Dessert;
		
		private bool _F_Lunch;
		
		private bool _F_SaladBar;
		
		private bool _F_Vegetarian;
		
		private bool _F_Disabled;
		
		private bool _F_DisabledWC;
		
		private bool _F_Pizzas;
		
		private bool _F_Weekends;
		
		private bool _F_FastFood;
		
		private bool _F_StudentBenefits;
		
		private bool _F_Delivery;
		
		private System.Nullable<double> _DistanceKm;
		
		private System.Nullable<double> _DistanceM;
		
		public fn_GetRestaurantsInRadiusResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string R_Name
		{
			get
			{
				return this._R_Name;
			}
			set
			{
				if ((this._R_Name != value))
				{
					this._R_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Address", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string R_Address
		{
			get
			{
				return this._R_Address;
			}
			set
			{
				if ((this._R_Address != value))
				{
					this._R_Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Phone", DbType="NVarChar(15)")]
		public string R_Phone
		{
			get
			{
				return this._R_Phone;
			}
			set
			{
				if ((this._R_Phone != value))
				{
					this._R_Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Price", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> R_Price
		{
			get
			{
				return this._R_Price;
			}
			set
			{
				if ((this._R_Price != value))
				{
					this._R_Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_CoordinateX", DbType="Decimal(18,14) NOT NULL")]
		public decimal R_CoordinateX
		{
			get
			{
				return this._R_CoordinateX;
			}
			set
			{
				if ((this._R_CoordinateX != value))
				{
					this._R_CoordinateX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_CoordinateY", DbType="Decimal(18,14) NOT NULL")]
		public decimal R_CoordinateY
		{
			get
			{
				return this._R_CoordinateY;
			}
			set
			{
				if ((this._R_CoordinateY != value))
				{
					this._R_CoordinateY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_UpdatedOn", DbType="Date NOT NULL")]
		public System.DateTime R_UpdatedOn
		{
			get
			{
				return this._R_UpdatedOn;
			}
			set
			{
				if ((this._R_UpdatedOn != value))
				{
					this._R_UpdatedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_WeekStart", DbType="Time")]
		public System.Nullable<System.TimeSpan> O_WeekStart
		{
			get
			{
				return this._O_WeekStart;
			}
			set
			{
				if ((this._O_WeekStart != value))
				{
					this._O_WeekStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_WeekEnd", DbType="Time")]
		public System.Nullable<System.TimeSpan> O_WeekEnd
		{
			get
			{
				return this._O_WeekEnd;
			}
			set
			{
				if ((this._O_WeekEnd != value))
				{
					this._O_WeekEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SaturdayStart", DbType="Time")]
		public System.Nullable<System.TimeSpan> O_SaturdayStart
		{
			get
			{
				return this._O_SaturdayStart;
			}
			set
			{
				if ((this._O_SaturdayStart != value))
				{
					this._O_SaturdayStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SaturdayEnd", DbType="Time")]
		public System.Nullable<System.TimeSpan> O_SaturdayEnd
		{
			get
			{
				return this._O_SaturdayEnd;
			}
			set
			{
				if ((this._O_SaturdayEnd != value))
				{
					this._O_SaturdayEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SundayStart", DbType="Time")]
		public System.Nullable<System.TimeSpan> O_SundayStart
		{
			get
			{
				return this._O_SundayStart;
			}
			set
			{
				if ((this._O_SundayStart != value))
				{
					this._O_SundayStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SundayEnd", DbType="Time")]
		public System.Nullable<System.TimeSpan> O_SundayEnd
		{
			get
			{
				return this._O_SundayEnd;
			}
			set
			{
				if ((this._O_SundayEnd != value))
				{
					this._O_SundayEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_Soup", DbType="NVarChar(100)")]
		public string M_Soup
		{
			get
			{
				return this._M_Soup;
			}
			set
			{
				if ((this._M_Soup != value))
				{
					this._M_Soup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_MainCourse", DbType="NVarChar(100)")]
		public string M_MainCourse
		{
			get
			{
				return this._M_MainCourse;
			}
			set
			{
				if ((this._M_MainCourse != value))
				{
					this._M_MainCourse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_Salad", DbType="NVarChar(100)")]
		public string M_Salad
		{
			get
			{
				return this._M_Salad;
			}
			set
			{
				if ((this._M_Salad != value))
				{
					this._M_Salad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_Dessert", DbType="NVarChar(100)")]
		public string M_Dessert
		{
			get
			{
				return this._M_Dessert;
			}
			set
			{
				if ((this._M_Dessert != value))
				{
					this._M_Dessert = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Lunch", DbType="Bit NOT NULL")]
		public bool F_Lunch
		{
			get
			{
				return this._F_Lunch;
			}
			set
			{
				if ((this._F_Lunch != value))
				{
					this._F_Lunch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_SaladBar", DbType="Bit NOT NULL")]
		public bool F_SaladBar
		{
			get
			{
				return this._F_SaladBar;
			}
			set
			{
				if ((this._F_SaladBar != value))
				{
					this._F_SaladBar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Vegetarian", DbType="Bit NOT NULL")]
		public bool F_Vegetarian
		{
			get
			{
				return this._F_Vegetarian;
			}
			set
			{
				if ((this._F_Vegetarian != value))
				{
					this._F_Vegetarian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Disabled", DbType="Bit NOT NULL")]
		public bool F_Disabled
		{
			get
			{
				return this._F_Disabled;
			}
			set
			{
				if ((this._F_Disabled != value))
				{
					this._F_Disabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_DisabledWC", DbType="Bit NOT NULL")]
		public bool F_DisabledWC
		{
			get
			{
				return this._F_DisabledWC;
			}
			set
			{
				if ((this._F_DisabledWC != value))
				{
					this._F_DisabledWC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Pizzas", DbType="Bit NOT NULL")]
		public bool F_Pizzas
		{
			get
			{
				return this._F_Pizzas;
			}
			set
			{
				if ((this._F_Pizzas != value))
				{
					this._F_Pizzas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Weekends", DbType="Bit NOT NULL")]
		public bool F_Weekends
		{
			get
			{
				return this._F_Weekends;
			}
			set
			{
				if ((this._F_Weekends != value))
				{
					this._F_Weekends = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_FastFood", DbType="Bit NOT NULL")]
		public bool F_FastFood
		{
			get
			{
				return this._F_FastFood;
			}
			set
			{
				if ((this._F_FastFood != value))
				{
					this._F_FastFood = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_StudentBenefits", DbType="Bit NOT NULL")]
		public bool F_StudentBenefits
		{
			get
			{
				return this._F_StudentBenefits;
			}
			set
			{
				if ((this._F_StudentBenefits != value))
				{
					this._F_StudentBenefits = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Delivery", DbType="Bit NOT NULL")]
		public bool F_Delivery
		{
			get
			{
				return this._F_Delivery;
			}
			set
			{
				if ((this._F_Delivery != value))
				{
					this._F_Delivery = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistanceKm", DbType="Float")]
		public System.Nullable<double> DistanceKm
		{
			get
			{
				return this._DistanceKm;
			}
			set
			{
				if ((this._DistanceKm != value))
				{
					this._DistanceKm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistanceM", DbType="Float")]
		public System.Nullable<double> DistanceM
		{
			get
			{
				return this._DistanceM;
			}
			set
			{
				if ((this._DistanceM != value))
				{
					this._DistanceM = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
