#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonParser
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BonDB")]
	public partial class BonDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFeature(Feature instance);
    partial void UpdateFeature(Feature instance);
    partial void DeleteFeature(Feature instance);
    partial void InsertMenu(Menu instance);
    partial void UpdateMenu(Menu instance);
    partial void DeleteMenu(Menu instance);
    partial void InsertOpening(Opening instance);
    partial void UpdateOpening(Opening instance);
    partial void DeleteOpening(Opening instance);
    partial void InsertRestaurant(Restaurant instance);
    partial void UpdateRestaurant(Restaurant instance);
    partial void DeleteRestaurant(Restaurant instance);
    #endregion
		
		public BonDataContext() : 
				base(global::BonParser.Properties.Settings.Default.BonDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BonDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BonDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<v_Restaurant> v_Restaurants
		{
			get
			{
				return this.GetTable<v_Restaurant>();
			}
		}
		
		public System.Data.Linq.Table<Feature> Features
		{
			get
			{
				return this.GetTable<Feature>();
			}
		}
		
		public System.Data.Linq.Table<Menu> Menus
		{
			get
			{
				return this.GetTable<Menu>();
			}
		}
		
		public System.Data.Linq.Table<Opening> Openings
		{
			get
			{
				return this.GetTable<Opening>();
			}
		}
		
		public System.Data.Linq.Table<Restaurant> Restaurants
		{
			get
			{
				return this.GetTable<Restaurant>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertFeature")]
		public int InsertFeature([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> lunch, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> saladBar, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> vegetarian, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> disabled, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> disabledWc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> pizzas, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> weekends, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> fastFood, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> studentBenefits, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> delivery, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] ref System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lunch, saladBar, vegetarian, disabled, disabledWc, pizzas, weekends, fastFood, studentBenefits, delivery, iD);
			iD = ((System.Nullable<int>)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertMenu")]
		public int InsertMenu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string soup, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string mainCourse, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string salad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string dessert, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] ref System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), soup, mainCourse, salad, dessert, iD);
			iD = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOpening")]
		public int InsertOpening([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> weekStart, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> weekEnd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> saturdayStart, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> saturdayEnd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> sundayStart, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Time")] System.Nullable<System.TimeSpan> sundayEnd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] ref System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), weekStart, weekEnd, saturdayStart, saturdayEnd, sundayStart, sundayEnd, iD);
			iD = ((System.Nullable<int>)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertRestaurant")]
		public int InsertRestaurant([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(15)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(4,2)")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,14)")] System.Nullable<decimal> coordinateX, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,14)")] System.Nullable<decimal> coordinateY, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> updatedOn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> menuID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> openingID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> featureID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, address, phone, price, coordinateX, coordinateY, updatedOn, menuID, openingID, featureID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TruncateAll")]
		public int TruncateAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_Restaurant")]
	public partial class v_Restaurant
	{
		
		private string _R_Name;
		
		private string _R_Address;
		
		private string _R_Phone;
		
		private decimal _R_Price;
		
		private decimal _R_CoordinateX;
		
		private decimal _R_CoordinateY;
		
		private System.DateTime _R_UpdatedOn;
		
		private System.Nullable<System.DateTime> _O_WeekStart;
		
		private System.Nullable<System.DateTime> _O_WeekEnd;
		
		private System.Nullable<System.DateTime> _O_SaturdayStart;
		
		private System.Nullable<System.DateTime> _O_SaturdayEnd;
		
		private System.Nullable<System.DateTime> _O_SundayStart;
		
		private System.Nullable<System.DateTime> _O_SundayEnd;
		
		private string _M_Soup;
		
		private string _M_MainCourse;
		
		private string _M_Salad;
		
		private string _M_Dessert;
		
		private bool _F_Lunch;
		
		private bool _F_SaladBar;
		
		private bool _F_Vegetarian;
		
		private bool _F_Disabled;
		
		private bool _F_DisabledWC;
		
		private bool _F_Pizzas;
		
		private bool _F_Weekends;
		
		private bool _F_FastFood;
		
		private bool _F_StudentBenefits;
		
		private bool _F_Delivery;
		
		public v_Restaurant()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string R_Name
		{
			get
			{
				return this._R_Name;
			}
			set
			{
				if ((this._R_Name != value))
				{
					this._R_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Address", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string R_Address
		{
			get
			{
				return this._R_Address;
			}
			set
			{
				if ((this._R_Address != value))
				{
					this._R_Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Phone", DbType="NVarChar(15)")]
		public string R_Phone
		{
			get
			{
				return this._R_Phone;
			}
			set
			{
				if ((this._R_Phone != value))
				{
					this._R_Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Price", DbType="Decimal(2,2) NOT NULL")]
		public decimal R_Price
		{
			get
			{
				return this._R_Price;
			}
			set
			{
				if ((this._R_Price != value))
				{
					this._R_Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_CoordinateX", DbType="Decimal(9,6) NOT NULL")]
		public decimal R_CoordinateX
		{
			get
			{
				return this._R_CoordinateX;
			}
			set
			{
				if ((this._R_CoordinateX != value))
				{
					this._R_CoordinateX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_CoordinateY", DbType="Decimal(9,6) NOT NULL")]
		public decimal R_CoordinateY
		{
			get
			{
				return this._R_CoordinateY;
			}
			set
			{
				if ((this._R_CoordinateY != value))
				{
					this._R_CoordinateY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_UpdatedOn", DbType="Date NOT NULL")]
		public System.DateTime R_UpdatedOn
		{
			get
			{
				return this._R_UpdatedOn;
			}
			set
			{
				if ((this._R_UpdatedOn != value))
				{
					this._R_UpdatedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_WeekStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_WeekStart
		{
			get
			{
				return this._O_WeekStart;
			}
			set
			{
				if ((this._O_WeekStart != value))
				{
					this._O_WeekStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_WeekEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_WeekEnd
		{
			get
			{
				return this._O_WeekEnd;
			}
			set
			{
				if ((this._O_WeekEnd != value))
				{
					this._O_WeekEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SaturdayStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_SaturdayStart
		{
			get
			{
				return this._O_SaturdayStart;
			}
			set
			{
				if ((this._O_SaturdayStart != value))
				{
					this._O_SaturdayStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SaturdayEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_SaturdayEnd
		{
			get
			{
				return this._O_SaturdayEnd;
			}
			set
			{
				if ((this._O_SaturdayEnd != value))
				{
					this._O_SaturdayEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SundayStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_SundayStart
		{
			get
			{
				return this._O_SundayStart;
			}
			set
			{
				if ((this._O_SundayStart != value))
				{
					this._O_SundayStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SundayEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_SundayEnd
		{
			get
			{
				return this._O_SundayEnd;
			}
			set
			{
				if ((this._O_SundayEnd != value))
				{
					this._O_SundayEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_Soup", DbType="NVarChar(100)")]
		public string M_Soup
		{
			get
			{
				return this._M_Soup;
			}
			set
			{
				if ((this._M_Soup != value))
				{
					this._M_Soup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_MainCourse", DbType="NVarChar(100)")]
		public string M_MainCourse
		{
			get
			{
				return this._M_MainCourse;
			}
			set
			{
				if ((this._M_MainCourse != value))
				{
					this._M_MainCourse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_Salad", DbType="NVarChar(100)")]
		public string M_Salad
		{
			get
			{
				return this._M_Salad;
			}
			set
			{
				if ((this._M_Salad != value))
				{
					this._M_Salad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_Dessert", DbType="NVarChar(100)")]
		public string M_Dessert
		{
			get
			{
				return this._M_Dessert;
			}
			set
			{
				if ((this._M_Dessert != value))
				{
					this._M_Dessert = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Lunch", DbType="Bit NOT NULL")]
		public bool F_Lunch
		{
			get
			{
				return this._F_Lunch;
			}
			set
			{
				if ((this._F_Lunch != value))
				{
					this._F_Lunch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_SaladBar", DbType="Bit NOT NULL")]
		public bool F_SaladBar
		{
			get
			{
				return this._F_SaladBar;
			}
			set
			{
				if ((this._F_SaladBar != value))
				{
					this._F_SaladBar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Vegetarian", DbType="Bit NOT NULL")]
		public bool F_Vegetarian
		{
			get
			{
				return this._F_Vegetarian;
			}
			set
			{
				if ((this._F_Vegetarian != value))
				{
					this._F_Vegetarian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Disabled", DbType="Bit NOT NULL")]
		public bool F_Disabled
		{
			get
			{
				return this._F_Disabled;
			}
			set
			{
				if ((this._F_Disabled != value))
				{
					this._F_Disabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_DisabledWC", DbType="Bit NOT NULL")]
		public bool F_DisabledWC
		{
			get
			{
				return this._F_DisabledWC;
			}
			set
			{
				if ((this._F_DisabledWC != value))
				{
					this._F_DisabledWC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Pizzas", DbType="Bit NOT NULL")]
		public bool F_Pizzas
		{
			get
			{
				return this._F_Pizzas;
			}
			set
			{
				if ((this._F_Pizzas != value))
				{
					this._F_Pizzas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Weekends", DbType="Bit NOT NULL")]
		public bool F_Weekends
		{
			get
			{
				return this._F_Weekends;
			}
			set
			{
				if ((this._F_Weekends != value))
				{
					this._F_Weekends = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_FastFood", DbType="Bit NOT NULL")]
		public bool F_FastFood
		{
			get
			{
				return this._F_FastFood;
			}
			set
			{
				if ((this._F_FastFood != value))
				{
					this._F_FastFood = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_StudentBenefits", DbType="Bit NOT NULL")]
		public bool F_StudentBenefits
		{
			get
			{
				return this._F_StudentBenefits;
			}
			set
			{
				if ((this._F_StudentBenefits != value))
				{
					this._F_StudentBenefits = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Delivery", DbType="Bit NOT NULL")]
		public bool F_Delivery
		{
			get
			{
				return this._F_Delivery;
			}
			set
			{
				if ((this._F_Delivery != value))
				{
					this._F_Delivery = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Feature")]
	public partial class Feature : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _F_ID;
		
		private bool _F_Lunch;
		
		private bool _F_SaladBar;
		
		private bool _F_Vegetarian;
		
		private bool _F_Disabled;
		
		private bool _F_DisabledWC;
		
		private bool _F_Pizzas;
		
		private bool _F_Weekends;
		
		private bool _F_FastFood;
		
		private bool _F_StudentBenefits;
		
		private bool _F_Delivery;
		
		private EntitySet<Restaurant> _Restaurants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnF_IDChanging(int value);
    partial void OnF_IDChanged();
    partial void OnF_LunchChanging(bool value);
    partial void OnF_LunchChanged();
    partial void OnF_SaladBarChanging(bool value);
    partial void OnF_SaladBarChanged();
    partial void OnF_VegetarianChanging(bool value);
    partial void OnF_VegetarianChanged();
    partial void OnF_DisabledChanging(bool value);
    partial void OnF_DisabledChanged();
    partial void OnF_DisabledWCChanging(bool value);
    partial void OnF_DisabledWCChanged();
    partial void OnF_PizzasChanging(bool value);
    partial void OnF_PizzasChanged();
    partial void OnF_WeekendsChanging(bool value);
    partial void OnF_WeekendsChanged();
    partial void OnF_FastFoodChanging(bool value);
    partial void OnF_FastFoodChanged();
    partial void OnF_StudentBenefitsChanging(bool value);
    partial void OnF_StudentBenefitsChanged();
    partial void OnF_DeliveryChanging(bool value);
    partial void OnF_DeliveryChanged();
    #endregion
		
		public Feature()
		{
			this._Restaurants = new EntitySet<Restaurant>(new Action<Restaurant>(this.attach_Restaurants), new Action<Restaurant>(this.detach_Restaurants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int F_ID
		{
			get
			{
				return this._F_ID;
			}
			set
			{
				if ((this._F_ID != value))
				{
					this.OnF_IDChanging(value);
					this.SendPropertyChanging();
					this._F_ID = value;
					this.SendPropertyChanged("F_ID");
					this.OnF_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Lunch", DbType="Bit NOT NULL")]
		public bool F_Lunch
		{
			get
			{
				return this._F_Lunch;
			}
			set
			{
				if ((this._F_Lunch != value))
				{
					this.OnF_LunchChanging(value);
					this.SendPropertyChanging();
					this._F_Lunch = value;
					this.SendPropertyChanged("F_Lunch");
					this.OnF_LunchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_SaladBar", DbType="Bit NOT NULL")]
		public bool F_SaladBar
		{
			get
			{
				return this._F_SaladBar;
			}
			set
			{
				if ((this._F_SaladBar != value))
				{
					this.OnF_SaladBarChanging(value);
					this.SendPropertyChanging();
					this._F_SaladBar = value;
					this.SendPropertyChanged("F_SaladBar");
					this.OnF_SaladBarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Vegetarian", DbType="Bit NOT NULL")]
		public bool F_Vegetarian
		{
			get
			{
				return this._F_Vegetarian;
			}
			set
			{
				if ((this._F_Vegetarian != value))
				{
					this.OnF_VegetarianChanging(value);
					this.SendPropertyChanging();
					this._F_Vegetarian = value;
					this.SendPropertyChanged("F_Vegetarian");
					this.OnF_VegetarianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Disabled", DbType="Bit NOT NULL")]
		public bool F_Disabled
		{
			get
			{
				return this._F_Disabled;
			}
			set
			{
				if ((this._F_Disabled != value))
				{
					this.OnF_DisabledChanging(value);
					this.SendPropertyChanging();
					this._F_Disabled = value;
					this.SendPropertyChanged("F_Disabled");
					this.OnF_DisabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_DisabledWC", DbType="Bit NOT NULL")]
		public bool F_DisabledWC
		{
			get
			{
				return this._F_DisabledWC;
			}
			set
			{
				if ((this._F_DisabledWC != value))
				{
					this.OnF_DisabledWCChanging(value);
					this.SendPropertyChanging();
					this._F_DisabledWC = value;
					this.SendPropertyChanged("F_DisabledWC");
					this.OnF_DisabledWCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Pizzas", DbType="Bit NOT NULL")]
		public bool F_Pizzas
		{
			get
			{
				return this._F_Pizzas;
			}
			set
			{
				if ((this._F_Pizzas != value))
				{
					this.OnF_PizzasChanging(value);
					this.SendPropertyChanging();
					this._F_Pizzas = value;
					this.SendPropertyChanged("F_Pizzas");
					this.OnF_PizzasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Weekends", DbType="Bit NOT NULL")]
		public bool F_Weekends
		{
			get
			{
				return this._F_Weekends;
			}
			set
			{
				if ((this._F_Weekends != value))
				{
					this.OnF_WeekendsChanging(value);
					this.SendPropertyChanging();
					this._F_Weekends = value;
					this.SendPropertyChanged("F_Weekends");
					this.OnF_WeekendsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_FastFood", DbType="Bit NOT NULL")]
		public bool F_FastFood
		{
			get
			{
				return this._F_FastFood;
			}
			set
			{
				if ((this._F_FastFood != value))
				{
					this.OnF_FastFoodChanging(value);
					this.SendPropertyChanging();
					this._F_FastFood = value;
					this.SendPropertyChanged("F_FastFood");
					this.OnF_FastFoodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_StudentBenefits", DbType="Bit NOT NULL")]
		public bool F_StudentBenefits
		{
			get
			{
				return this._F_StudentBenefits;
			}
			set
			{
				if ((this._F_StudentBenefits != value))
				{
					this.OnF_StudentBenefitsChanging(value);
					this.SendPropertyChanging();
					this._F_StudentBenefits = value;
					this.SendPropertyChanged("F_StudentBenefits");
					this.OnF_StudentBenefitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Delivery", DbType="Bit NOT NULL")]
		public bool F_Delivery
		{
			get
			{
				return this._F_Delivery;
			}
			set
			{
				if ((this._F_Delivery != value))
				{
					this.OnF_DeliveryChanging(value);
					this.SendPropertyChanging();
					this._F_Delivery = value;
					this.SendPropertyChanged("F_Delivery");
					this.OnF_DeliveryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Feature_Restaurant", Storage="_Restaurants", ThisKey="F_ID", OtherKey="R_F_ID")]
		public EntitySet<Restaurant> Restaurants
		{
			get
			{
				return this._Restaurants;
			}
			set
			{
				this._Restaurants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Restaurants(Restaurant entity)
		{
			this.SendPropertyChanging();
			entity.Feature = this;
		}
		
		private void detach_Restaurants(Restaurant entity)
		{
			this.SendPropertyChanging();
			entity.Feature = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menu")]
	public partial class Menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _M_ID;
		
		private string _M_Soup;
		
		private string _M_MainCourse;
		
		private string _M_Salad;
		
		private string _M_Dessert;
		
		private EntitySet<Restaurant> _Restaurants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnM_IDChanging(int value);
    partial void OnM_IDChanged();
    partial void OnM_SoupChanging(string value);
    partial void OnM_SoupChanged();
    partial void OnM_MainCourseChanging(string value);
    partial void OnM_MainCourseChanged();
    partial void OnM_SaladChanging(string value);
    partial void OnM_SaladChanged();
    partial void OnM_DessertChanging(string value);
    partial void OnM_DessertChanged();
    #endregion
		
		public Menu()
		{
			this._Restaurants = new EntitySet<Restaurant>(new Action<Restaurant>(this.attach_Restaurants), new Action<Restaurant>(this.detach_Restaurants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int M_ID
		{
			get
			{
				return this._M_ID;
			}
			set
			{
				if ((this._M_ID != value))
				{
					this.OnM_IDChanging(value);
					this.SendPropertyChanging();
					this._M_ID = value;
					this.SendPropertyChanged("M_ID");
					this.OnM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_Soup", DbType="NVarChar(100)")]
		public string M_Soup
		{
			get
			{
				return this._M_Soup;
			}
			set
			{
				if ((this._M_Soup != value))
				{
					this.OnM_SoupChanging(value);
					this.SendPropertyChanging();
					this._M_Soup = value;
					this.SendPropertyChanged("M_Soup");
					this.OnM_SoupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_MainCourse", DbType="NVarChar(100)")]
		public string M_MainCourse
		{
			get
			{
				return this._M_MainCourse;
			}
			set
			{
				if ((this._M_MainCourse != value))
				{
					this.OnM_MainCourseChanging(value);
					this.SendPropertyChanging();
					this._M_MainCourse = value;
					this.SendPropertyChanged("M_MainCourse");
					this.OnM_MainCourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_Salad", DbType="NVarChar(100)")]
		public string M_Salad
		{
			get
			{
				return this._M_Salad;
			}
			set
			{
				if ((this._M_Salad != value))
				{
					this.OnM_SaladChanging(value);
					this.SendPropertyChanging();
					this._M_Salad = value;
					this.SendPropertyChanged("M_Salad");
					this.OnM_SaladChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_Dessert", DbType="NVarChar(100)")]
		public string M_Dessert
		{
			get
			{
				return this._M_Dessert;
			}
			set
			{
				if ((this._M_Dessert != value))
				{
					this.OnM_DessertChanging(value);
					this.SendPropertyChanging();
					this._M_Dessert = value;
					this.SendPropertyChanged("M_Dessert");
					this.OnM_DessertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menu_Restaurant", Storage="_Restaurants", ThisKey="M_ID", OtherKey="R_M_ID")]
		public EntitySet<Restaurant> Restaurants
		{
			get
			{
				return this._Restaurants;
			}
			set
			{
				this._Restaurants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Restaurants(Restaurant entity)
		{
			this.SendPropertyChanging();
			entity.Menu = this;
		}
		
		private void detach_Restaurants(Restaurant entity)
		{
			this.SendPropertyChanging();
			entity.Menu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Opening")]
	public partial class Opening : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _O_ID;
		
		private System.Nullable<System.TimeSpan> _O_WeekStart;
		
		private System.Nullable<System.TimeSpan> _O_WeekEnd;
		
		private System.Nullable<System.TimeSpan> _O_SaturdayStart;
		
		private System.Nullable<System.TimeSpan> _O_SaturdayEnd;
		
		private System.Nullable<System.TimeSpan> _O_SundayStart;
		
		private System.Nullable<System.TimeSpan> _O_SundayEnd;
		
		private EntitySet<Restaurant> _Restaurants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnO_IDChanging(int value);
    partial void OnO_IDChanged();
    partial void OnO_WeekStartChanging(System.Nullable<System.TimeSpan> value);
    partial void OnO_WeekStartChanged();
    partial void OnO_WeekEndChanging(System.Nullable<System.TimeSpan> value);
    partial void OnO_WeekEndChanged();
    partial void OnO_SaturdayStartChanging(System.Nullable<System.TimeSpan> value);
    partial void OnO_SaturdayStartChanged();
    partial void OnO_SaturdayEndChanging(System.Nullable<System.TimeSpan> value);
    partial void OnO_SaturdayEndChanged();
    partial void OnO_SundayStartChanging(System.Nullable<System.TimeSpan> value);
    partial void OnO_SundayStartChanged();
    partial void OnO_SundayEndChanging(System.Nullable<System.TimeSpan> value);
    partial void OnO_SundayEndChanged();
    #endregion
		
		public Opening()
		{
			this._Restaurants = new EntitySet<Restaurant>(new Action<Restaurant>(this.attach_Restaurants), new Action<Restaurant>(this.detach_Restaurants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int O_ID
		{
			get
			{
				return this._O_ID;
			}
			set
			{
				if ((this._O_ID != value))
				{
					this.OnO_IDChanging(value);
					this.SendPropertyChanging();
					this._O_ID = value;
					this.SendPropertyChanged("O_ID");
					this.OnO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_WeekStart", DbType="Time")]
		public System.Nullable<System.TimeSpan> O_WeekStart
		{
			get
			{
				return this._O_WeekStart;
			}
			set
			{
				if ((this._O_WeekStart != value))
				{
					this.OnO_WeekStartChanging(value);
					this.SendPropertyChanging();
					this._O_WeekStart = value;
					this.SendPropertyChanged("O_WeekStart");
					this.OnO_WeekStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_WeekEnd", DbType="Time")]
		public System.Nullable<System.TimeSpan> O_WeekEnd
		{
			get
			{
				return this._O_WeekEnd;
			}
			set
			{
				if ((this._O_WeekEnd != value))
				{
					this.OnO_WeekEndChanging(value);
					this.SendPropertyChanging();
					this._O_WeekEnd = value;
					this.SendPropertyChanged("O_WeekEnd");
					this.OnO_WeekEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SaturdayStart", DbType="Time")]
		public System.Nullable<System.TimeSpan> O_SaturdayStart
		{
			get
			{
				return this._O_SaturdayStart;
			}
			set
			{
				if ((this._O_SaturdayStart != value))
				{
					this.OnO_SaturdayStartChanging(value);
					this.SendPropertyChanging();
					this._O_SaturdayStart = value;
					this.SendPropertyChanged("O_SaturdayStart");
					this.OnO_SaturdayStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SaturdayEnd", DbType="Time")]
		public System.Nullable<System.TimeSpan> O_SaturdayEnd
		{
			get
			{
				return this._O_SaturdayEnd;
			}
			set
			{
				if ((this._O_SaturdayEnd != value))
				{
					this.OnO_SaturdayEndChanging(value);
					this.SendPropertyChanging();
					this._O_SaturdayEnd = value;
					this.SendPropertyChanged("O_SaturdayEnd");
					this.OnO_SaturdayEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SundayStart", DbType="Time")]
		public System.Nullable<System.TimeSpan> O_SundayStart
		{
			get
			{
				return this._O_SundayStart;
			}
			set
			{
				if ((this._O_SundayStart != value))
				{
					this.OnO_SundayStartChanging(value);
					this.SendPropertyChanging();
					this._O_SundayStart = value;
					this.SendPropertyChanged("O_SundayStart");
					this.OnO_SundayStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SundayEnd", DbType="Time")]
		public System.Nullable<System.TimeSpan> O_SundayEnd
		{
			get
			{
				return this._O_SundayEnd;
			}
			set
			{
				if ((this._O_SundayEnd != value))
				{
					this.OnO_SundayEndChanging(value);
					this.SendPropertyChanging();
					this._O_SundayEnd = value;
					this.SendPropertyChanged("O_SundayEnd");
					this.OnO_SundayEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Opening_Restaurant", Storage="_Restaurants", ThisKey="O_ID", OtherKey="R_O_ID")]
		public EntitySet<Restaurant> Restaurants
		{
			get
			{
				return this._Restaurants;
			}
			set
			{
				this._Restaurants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Restaurants(Restaurant entity)
		{
			this.SendPropertyChanging();
			entity.Opening = this;
		}
		
		private void detach_Restaurants(Restaurant entity)
		{
			this.SendPropertyChanging();
			entity.Opening = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Restaurant")]
	public partial class Restaurant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _R_ID;
		
		private string _R_Name;
		
		private string _R_Address;
		
		private string _R_Phone;
		
		private System.Nullable<decimal> _R_Price;
		
		private decimal _R_CoordinateX;
		
		private decimal _R_CoordinateY;
		
		private System.DateTime _R_UpdatedOn;
		
		private System.Nullable<int> _R_M_ID;
		
		private int _R_O_ID;
		
		private int _R_F_ID;
		
		private EntityRef<Feature> _Feature;
		
		private EntityRef<Menu> _Menu;
		
		private EntityRef<Opening> _Opening;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnR_IDChanging(int value);
    partial void OnR_IDChanged();
    partial void OnR_NameChanging(string value);
    partial void OnR_NameChanged();
    partial void OnR_AddressChanging(string value);
    partial void OnR_AddressChanged();
    partial void OnR_PhoneChanging(string value);
    partial void OnR_PhoneChanged();
    partial void OnR_PriceChanging(System.Nullable<decimal> value);
    partial void OnR_PriceChanged();
    partial void OnR_CoordinateXChanging(decimal value);
    partial void OnR_CoordinateXChanged();
    partial void OnR_CoordinateYChanging(decimal value);
    partial void OnR_CoordinateYChanged();
    partial void OnR_UpdatedOnChanging(System.DateTime value);
    partial void OnR_UpdatedOnChanged();
    partial void OnR_M_IDChanging(System.Nullable<int> value);
    partial void OnR_M_IDChanged();
    partial void OnR_O_IDChanging(int value);
    partial void OnR_O_IDChanged();
    partial void OnR_F_IDChanging(int value);
    partial void OnR_F_IDChanged();
    #endregion
		
		public Restaurant()
		{
			this._Feature = default(EntityRef<Feature>);
			this._Menu = default(EntityRef<Menu>);
			this._Opening = default(EntityRef<Opening>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int R_ID
		{
			get
			{
				return this._R_ID;
			}
			set
			{
				if ((this._R_ID != value))
				{
					this.OnR_IDChanging(value);
					this.SendPropertyChanging();
					this._R_ID = value;
					this.SendPropertyChanged("R_ID");
					this.OnR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string R_Name
		{
			get
			{
				return this._R_Name;
			}
			set
			{
				if ((this._R_Name != value))
				{
					this.OnR_NameChanging(value);
					this.SendPropertyChanging();
					this._R_Name = value;
					this.SendPropertyChanged("R_Name");
					this.OnR_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Address", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string R_Address
		{
			get
			{
				return this._R_Address;
			}
			set
			{
				if ((this._R_Address != value))
				{
					this.OnR_AddressChanging(value);
					this.SendPropertyChanging();
					this._R_Address = value;
					this.SendPropertyChanged("R_Address");
					this.OnR_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Phone", DbType="NVarChar(15)")]
		public string R_Phone
		{
			get
			{
				return this._R_Phone;
			}
			set
			{
				if ((this._R_Phone != value))
				{
					this.OnR_PhoneChanging(value);
					this.SendPropertyChanging();
					this._R_Phone = value;
					this.SendPropertyChanged("R_Phone");
					this.OnR_PhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Price", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> R_Price
		{
			get
			{
				return this._R_Price;
			}
			set
			{
				if ((this._R_Price != value))
				{
					this.OnR_PriceChanging(value);
					this.SendPropertyChanging();
					this._R_Price = value;
					this.SendPropertyChanged("R_Price");
					this.OnR_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_CoordinateX", DbType="Decimal(18,14) NOT NULL")]
		public decimal R_CoordinateX
		{
			get
			{
				return this._R_CoordinateX;
			}
			set
			{
				if ((this._R_CoordinateX != value))
				{
					this.OnR_CoordinateXChanging(value);
					this.SendPropertyChanging();
					this._R_CoordinateX = value;
					this.SendPropertyChanged("R_CoordinateX");
					this.OnR_CoordinateXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_CoordinateY", DbType="Decimal(18,14) NOT NULL")]
		public decimal R_CoordinateY
		{
			get
			{
				return this._R_CoordinateY;
			}
			set
			{
				if ((this._R_CoordinateY != value))
				{
					this.OnR_CoordinateYChanging(value);
					this.SendPropertyChanging();
					this._R_CoordinateY = value;
					this.SendPropertyChanged("R_CoordinateY");
					this.OnR_CoordinateYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_UpdatedOn", DbType="Date NOT NULL")]
		public System.DateTime R_UpdatedOn
		{
			get
			{
				return this._R_UpdatedOn;
			}
			set
			{
				if ((this._R_UpdatedOn != value))
				{
					this.OnR_UpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._R_UpdatedOn = value;
					this.SendPropertyChanged("R_UpdatedOn");
					this.OnR_UpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_M_ID", DbType="Int")]
		public System.Nullable<int> R_M_ID
		{
			get
			{
				return this._R_M_ID;
			}
			set
			{
				if ((this._R_M_ID != value))
				{
					if (this._Menu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnR_M_IDChanging(value);
					this.SendPropertyChanging();
					this._R_M_ID = value;
					this.SendPropertyChanged("R_M_ID");
					this.OnR_M_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_O_ID", DbType="Int NOT NULL")]
		public int R_O_ID
		{
			get
			{
				return this._R_O_ID;
			}
			set
			{
				if ((this._R_O_ID != value))
				{
					if (this._Opening.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnR_O_IDChanging(value);
					this.SendPropertyChanging();
					this._R_O_ID = value;
					this.SendPropertyChanged("R_O_ID");
					this.OnR_O_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_F_ID", DbType="Int NOT NULL")]
		public int R_F_ID
		{
			get
			{
				return this._R_F_ID;
			}
			set
			{
				if ((this._R_F_ID != value))
				{
					if (this._Feature.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnR_F_IDChanging(value);
					this.SendPropertyChanging();
					this._R_F_ID = value;
					this.SendPropertyChanged("R_F_ID");
					this.OnR_F_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Feature_Restaurant", Storage="_Feature", ThisKey="R_F_ID", OtherKey="F_ID", IsForeignKey=true)]
		public Feature Feature
		{
			get
			{
				return this._Feature.Entity;
			}
			set
			{
				Feature previousValue = this._Feature.Entity;
				if (((previousValue != value) 
							|| (this._Feature.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Feature.Entity = null;
						previousValue.Restaurants.Remove(this);
					}
					this._Feature.Entity = value;
					if ((value != null))
					{
						value.Restaurants.Add(this);
						this._R_F_ID = value.F_ID;
					}
					else
					{
						this._R_F_ID = default(int);
					}
					this.SendPropertyChanged("Feature");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menu_Restaurant", Storage="_Menu", ThisKey="R_M_ID", OtherKey="M_ID", IsForeignKey=true)]
		public Menu Menu
		{
			get
			{
				return this._Menu.Entity;
			}
			set
			{
				Menu previousValue = this._Menu.Entity;
				if (((previousValue != value) 
							|| (this._Menu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Menu.Entity = null;
						previousValue.Restaurants.Remove(this);
					}
					this._Menu.Entity = value;
					if ((value != null))
					{
						value.Restaurants.Add(this);
						this._R_M_ID = value.M_ID;
					}
					else
					{
						this._R_M_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Menu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Opening_Restaurant", Storage="_Opening", ThisKey="R_O_ID", OtherKey="O_ID", IsForeignKey=true)]
		public Opening Opening
		{
			get
			{
				return this._Opening.Entity;
			}
			set
			{
				Opening previousValue = this._Opening.Entity;
				if (((previousValue != value) 
							|| (this._Opening.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Opening.Entity = null;
						previousValue.Restaurants.Remove(this);
					}
					this._Opening.Entity = value;
					if ((value != null))
					{
						value.Restaurants.Add(this);
						this._R_O_ID = value.O_ID;
					}
					else
					{
						this._R_O_ID = default(int);
					}
					this.SendPropertyChanged("Opening");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
