#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BonDB")]
	public partial class BonDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BonDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BonDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BonDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BonDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<v_Restaurant> v_Restaurants
		{
			get
			{
				return this.GetTable<v_Restaurant>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_Restaurant")]
	public partial class v_Restaurant
	{
		
		private string _R_Name;
		
		private string _R_Address;
		
		private string _R_Phone;
		
		private decimal _R_Price;
		
		private decimal _R_CoordinateX;
		
		private decimal _R_CoordinateY;
		
		private System.DateTime _R_UpdatedOn;
		
		private System.Nullable<System.DateTime> _O_WeekStart;
		
		private System.Nullable<System.DateTime> _O_WeekEnd;
		
		private System.Nullable<System.DateTime> _O_SaturdayStart;
		
		private System.Nullable<System.DateTime> _O_SaturdayEnd;
		
		private System.Nullable<System.DateTime> _O_SundayStart;
		
		private System.Nullable<System.DateTime> _O_SundayEnd;
		
		private string _M_Soup;
		
		private string _M_MainCourse;
		
		private string _M_Salad;
		
		private string _M_Dessert;
		
		private bool _F_Lunch;
		
		private bool _F_SaladBar;
		
		private bool _F_Vegetarian;
		
		private bool _F_Disabled;
		
		private bool _F_DisabledWC;
		
		private bool _F_Pizzas;
		
		private bool _F_Weekends;
		
		private bool _F_FastFood;
		
		private bool _F_StudentBenefits;
		
		private bool _F_Delivery;
		
		public v_Restaurant()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string R_Name
		{
			get
			{
				return this._R_Name;
			}
			set
			{
				if ((this._R_Name != value))
				{
					this._R_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Address", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string R_Address
		{
			get
			{
				return this._R_Address;
			}
			set
			{
				if ((this._R_Address != value))
				{
					this._R_Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Phone", DbType="NVarChar(15)")]
		public string R_Phone
		{
			get
			{
				return this._R_Phone;
			}
			set
			{
				if ((this._R_Phone != value))
				{
					this._R_Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Price", DbType="Decimal(2,2) NOT NULL")]
		public decimal R_Price
		{
			get
			{
				return this._R_Price;
			}
			set
			{
				if ((this._R_Price != value))
				{
					this._R_Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_CoordinateX", DbType="Decimal(9,6) NOT NULL")]
		public decimal R_CoordinateX
		{
			get
			{
				return this._R_CoordinateX;
			}
			set
			{
				if ((this._R_CoordinateX != value))
				{
					this._R_CoordinateX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_CoordinateY", DbType="Decimal(9,6) NOT NULL")]
		public decimal R_CoordinateY
		{
			get
			{
				return this._R_CoordinateY;
			}
			set
			{
				if ((this._R_CoordinateY != value))
				{
					this._R_CoordinateY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_UpdatedOn", DbType="Date NOT NULL")]
		public System.DateTime R_UpdatedOn
		{
			get
			{
				return this._R_UpdatedOn;
			}
			set
			{
				if ((this._R_UpdatedOn != value))
				{
					this._R_UpdatedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_WeekStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_WeekStart
		{
			get
			{
				return this._O_WeekStart;
			}
			set
			{
				if ((this._O_WeekStart != value))
				{
					this._O_WeekStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_WeekEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_WeekEnd
		{
			get
			{
				return this._O_WeekEnd;
			}
			set
			{
				if ((this._O_WeekEnd != value))
				{
					this._O_WeekEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SaturdayStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_SaturdayStart
		{
			get
			{
				return this._O_SaturdayStart;
			}
			set
			{
				if ((this._O_SaturdayStart != value))
				{
					this._O_SaturdayStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SaturdayEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_SaturdayEnd
		{
			get
			{
				return this._O_SaturdayEnd;
			}
			set
			{
				if ((this._O_SaturdayEnd != value))
				{
					this._O_SaturdayEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SundayStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_SundayStart
		{
			get
			{
				return this._O_SundayStart;
			}
			set
			{
				if ((this._O_SundayStart != value))
				{
					this._O_SundayStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_SundayEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> O_SundayEnd
		{
			get
			{
				return this._O_SundayEnd;
			}
			set
			{
				if ((this._O_SundayEnd != value))
				{
					this._O_SundayEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_Soup", DbType="NVarChar(100)")]
		public string M_Soup
		{
			get
			{
				return this._M_Soup;
			}
			set
			{
				if ((this._M_Soup != value))
				{
					this._M_Soup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_MainCourse", DbType="NVarChar(100)")]
		public string M_MainCourse
		{
			get
			{
				return this._M_MainCourse;
			}
			set
			{
				if ((this._M_MainCourse != value))
				{
					this._M_MainCourse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_Salad", DbType="NVarChar(100)")]
		public string M_Salad
		{
			get
			{
				return this._M_Salad;
			}
			set
			{
				if ((this._M_Salad != value))
				{
					this._M_Salad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_Dessert", DbType="NVarChar(100)")]
		public string M_Dessert
		{
			get
			{
				return this._M_Dessert;
			}
			set
			{
				if ((this._M_Dessert != value))
				{
					this._M_Dessert = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Lunch", DbType="Bit NOT NULL")]
		public bool F_Lunch
		{
			get
			{
				return this._F_Lunch;
			}
			set
			{
				if ((this._F_Lunch != value))
				{
					this._F_Lunch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_SaladBar", DbType="Bit NOT NULL")]
		public bool F_SaladBar
		{
			get
			{
				return this._F_SaladBar;
			}
			set
			{
				if ((this._F_SaladBar != value))
				{
					this._F_SaladBar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Vegetarian", DbType="Bit NOT NULL")]
		public bool F_Vegetarian
		{
			get
			{
				return this._F_Vegetarian;
			}
			set
			{
				if ((this._F_Vegetarian != value))
				{
					this._F_Vegetarian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Disabled", DbType="Bit NOT NULL")]
		public bool F_Disabled
		{
			get
			{
				return this._F_Disabled;
			}
			set
			{
				if ((this._F_Disabled != value))
				{
					this._F_Disabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_DisabledWC", DbType="Bit NOT NULL")]
		public bool F_DisabledWC
		{
			get
			{
				return this._F_DisabledWC;
			}
			set
			{
				if ((this._F_DisabledWC != value))
				{
					this._F_DisabledWC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Pizzas", DbType="Bit NOT NULL")]
		public bool F_Pizzas
		{
			get
			{
				return this._F_Pizzas;
			}
			set
			{
				if ((this._F_Pizzas != value))
				{
					this._F_Pizzas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Weekends", DbType="Bit NOT NULL")]
		public bool F_Weekends
		{
			get
			{
				return this._F_Weekends;
			}
			set
			{
				if ((this._F_Weekends != value))
				{
					this._F_Weekends = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_FastFood", DbType="Bit NOT NULL")]
		public bool F_FastFood
		{
			get
			{
				return this._F_FastFood;
			}
			set
			{
				if ((this._F_FastFood != value))
				{
					this._F_FastFood = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_StudentBenefits", DbType="Bit NOT NULL")]
		public bool F_StudentBenefits
		{
			get
			{
				return this._F_StudentBenefits;
			}
			set
			{
				if ((this._F_StudentBenefits != value))
				{
					this._F_StudentBenefits = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Delivery", DbType="Bit NOT NULL")]
		public bool F_Delivery
		{
			get
			{
				return this._F_Delivery;
			}
			set
			{
				if ((this._F_Delivery != value))
				{
					this._F_Delivery = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
