<?xml version="1.0" encoding="utf-8"?><Database Name="BonDB" Class="BonDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=bondb.database.windows.net;Initial Catalog=BonDB;User ID=peroxy;Connect Timeout=60" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BonDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.v_Restaurant" Member="v_Restaurants">
    <Type Name="v_Restaurant">
      <Column Name="R_Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="R_Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="R_Phone" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="R_Price" Type="System.Decimal" DbType="Decimal(2,2) NOT NULL" CanBeNull="false" />
      <Column Name="R_CoordinateX" Type="System.Decimal" DbType="Decimal(9,6) NOT NULL" CanBeNull="false" />
      <Column Name="R_CoordinateY" Type="System.Decimal" DbType="Decimal(9,6) NOT NULL" CanBeNull="false" />
      <Column Name="R_UpdatedOn" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="O_WeekStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="O_WeekEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="O_SaturdayStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="O_SaturdayEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="O_SundayStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="O_SundayEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="M_Soup" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="M_MainCourse" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="M_Salad" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="M_Dessert" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="F_Lunch" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="F_SaladBar" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="F_Vegetarian" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="F_Disabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="F_DisabledWC" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="F_Pizzas" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="F_Weekends" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="F_FastFood" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="F_StudentBenefits" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="F_Delivery" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>