//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonRestApi.BonWs {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Restaurants", Namespace="http://schemas.datacontract.org/2004/07/BonService")]
    [System.SerializableAttribute()]
    public partial class Restaurants : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BonRestApi.BonWs.Restaurant[] ValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BonRestApi.BonWs.Restaurant[] Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Restaurant", Namespace="http://schemas.datacontract.org/2004/07/BonService")]
    [System.SerializableAttribute()]
    public partial class Restaurant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CoordinateXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CoordinateYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasDeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasDisabledSupportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasDisabledWcSupportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasSaladBarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasStudentBenefitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasVegetarianSupportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BonRestApi.BonWs.Menu MenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OpenDuringWeekendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BonRestApi.BonWs.OpeningTime OpeningTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ServesFastFoodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ServesLunchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ServesPizzasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CoordinateX {
            get {
                return this.CoordinateXField;
            }
            set {
                if ((this.CoordinateXField.Equals(value) != true)) {
                    this.CoordinateXField = value;
                    this.RaisePropertyChanged("CoordinateX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CoordinateY {
            get {
                return this.CoordinateYField;
            }
            set {
                if ((this.CoordinateYField.Equals(value) != true)) {
                    this.CoordinateYField = value;
                    this.RaisePropertyChanged("CoordinateY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDelivery {
            get {
                return this.HasDeliveryField;
            }
            set {
                if ((this.HasDeliveryField.Equals(value) != true)) {
                    this.HasDeliveryField = value;
                    this.RaisePropertyChanged("HasDelivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDisabledSupport {
            get {
                return this.HasDisabledSupportField;
            }
            set {
                if ((this.HasDisabledSupportField.Equals(value) != true)) {
                    this.HasDisabledSupportField = value;
                    this.RaisePropertyChanged("HasDisabledSupport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDisabledWcSupport {
            get {
                return this.HasDisabledWcSupportField;
            }
            set {
                if ((this.HasDisabledWcSupportField.Equals(value) != true)) {
                    this.HasDisabledWcSupportField = value;
                    this.RaisePropertyChanged("HasDisabledWcSupport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSaladBar {
            get {
                return this.HasSaladBarField;
            }
            set {
                if ((this.HasSaladBarField.Equals(value) != true)) {
                    this.HasSaladBarField = value;
                    this.RaisePropertyChanged("HasSaladBar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasStudentBenefits {
            get {
                return this.HasStudentBenefitsField;
            }
            set {
                if ((this.HasStudentBenefitsField.Equals(value) != true)) {
                    this.HasStudentBenefitsField = value;
                    this.RaisePropertyChanged("HasStudentBenefits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasVegetarianSupport {
            get {
                return this.HasVegetarianSupportField;
            }
            set {
                if ((this.HasVegetarianSupportField.Equals(value) != true)) {
                    this.HasVegetarianSupportField = value;
                    this.RaisePropertyChanged("HasVegetarianSupport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BonRestApi.BonWs.Menu Menu {
            get {
                return this.MenuField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuField, value) != true)) {
                    this.MenuField = value;
                    this.RaisePropertyChanged("Menu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OpenDuringWeekends {
            get {
                return this.OpenDuringWeekendsField;
            }
            set {
                if ((this.OpenDuringWeekendsField.Equals(value) != true)) {
                    this.OpenDuringWeekendsField = value;
                    this.RaisePropertyChanged("OpenDuringWeekends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BonRestApi.BonWs.OpeningTime OpeningTime {
            get {
                return this.OpeningTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.OpeningTimeField, value) != true)) {
                    this.OpeningTimeField = value;
                    this.RaisePropertyChanged("OpeningTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServesFastFood {
            get {
                return this.ServesFastFoodField;
            }
            set {
                if ((this.ServesFastFoodField.Equals(value) != true)) {
                    this.ServesFastFoodField = value;
                    this.RaisePropertyChanged("ServesFastFood");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServesLunch {
            get {
                return this.ServesLunchField;
            }
            set {
                if ((this.ServesLunchField.Equals(value) != true)) {
                    this.ServesLunchField = value;
                    this.RaisePropertyChanged("ServesLunch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServesPizzas {
            get {
                return this.ServesPizzasField;
            }
            set {
                if ((this.ServesPizzasField.Equals(value) != true)) {
                    this.ServesPizzasField = value;
                    this.RaisePropertyChanged("ServesPizzas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedOn {
            get {
                return this.UpdatedOnField;
            }
            set {
                if ((this.UpdatedOnField.Equals(value) != true)) {
                    this.UpdatedOnField = value;
                    this.RaisePropertyChanged("UpdatedOn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Menu", Namespace="http://schemas.datacontract.org/2004/07/BonService")]
    [System.SerializableAttribute()]
    public partial class Menu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DessertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MainCourseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaladField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoupField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dessert {
            get {
                return this.DessertField;
            }
            set {
                if ((object.ReferenceEquals(this.DessertField, value) != true)) {
                    this.DessertField = value;
                    this.RaisePropertyChanged("Dessert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainCourse {
            get {
                return this.MainCourseField;
            }
            set {
                if ((object.ReferenceEquals(this.MainCourseField, value) != true)) {
                    this.MainCourseField = value;
                    this.RaisePropertyChanged("MainCourse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salad {
            get {
                return this.SaladField;
            }
            set {
                if ((object.ReferenceEquals(this.SaladField, value) != true)) {
                    this.SaladField = value;
                    this.RaisePropertyChanged("Salad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soup {
            get {
                return this.SoupField;
            }
            set {
                if ((object.ReferenceEquals(this.SoupField, value) != true)) {
                    this.SoupField = value;
                    this.RaisePropertyChanged("Soup");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpeningTime", Namespace="http://schemas.datacontract.org/2004/07/BonService")]
    [System.SerializableAttribute()]
    public partial class OpeningTime : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BonRestApi.BonWs.Saturday SaturdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BonRestApi.BonWs.Sunday SundayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BonRestApi.BonWs.Week WeekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BonRestApi.BonWs.Saturday Saturday {
            get {
                return this.SaturdayField;
            }
            set {
                if ((object.ReferenceEquals(this.SaturdayField, value) != true)) {
                    this.SaturdayField = value;
                    this.RaisePropertyChanged("Saturday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BonRestApi.BonWs.Sunday Sunday {
            get {
                return this.SundayField;
            }
            set {
                if ((object.ReferenceEquals(this.SundayField, value) != true)) {
                    this.SundayField = value;
                    this.RaisePropertyChanged("Sunday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BonRestApi.BonWs.Week Week {
            get {
                return this.WeekField;
            }
            set {
                if ((object.ReferenceEquals(this.WeekField, value) != true)) {
                    this.WeekField = value;
                    this.RaisePropertyChanged("Week");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Saturday", Namespace="http://schemas.datacontract.org/2004/07/BonService")]
    [System.SerializableAttribute()]
    public partial class Saturday : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> From {
            get {
                return this.FromField;
            }
            set {
                if ((this.FromField.Equals(value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> To {
            get {
                return this.ToField;
            }
            set {
                if ((this.ToField.Equals(value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sunday", Namespace="http://schemas.datacontract.org/2004/07/BonService")]
    [System.SerializableAttribute()]
    public partial class Sunday : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> From {
            get {
                return this.FromField;
            }
            set {
                if ((this.FromField.Equals(value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> To {
            get {
                return this.ToField;
            }
            set {
                if ((this.ToField.Equals(value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Week", Namespace="http://schemas.datacontract.org/2004/07/BonService")]
    [System.SerializableAttribute()]
    public partial class Week : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> From {
            get {
                return this.FromField;
            }
            set {
                if ((this.FromField.Equals(value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> To {
            get {
                return this.ToField;
            }
            set {
                if ((this.ToField.Equals(value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filter", Namespace="http://schemas.datacontract.org/2004/07/BonService")]
    [System.SerializableAttribute()]
    public partial class Filter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasDeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasDisabledSupportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasDisabledWcSupportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasSaladBarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasStudentBenefitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasVegetarianSupportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OpenDuringWeekendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BonRestApi.BonWs.OpeningTime OpeningTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BonRestApi.BonWs.Price PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ServesFastFoodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ServesLunchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ServesPizzasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDelivery {
            get {
                return this.HasDeliveryField;
            }
            set {
                if ((this.HasDeliveryField.Equals(value) != true)) {
                    this.HasDeliveryField = value;
                    this.RaisePropertyChanged("HasDelivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDisabledSupport {
            get {
                return this.HasDisabledSupportField;
            }
            set {
                if ((this.HasDisabledSupportField.Equals(value) != true)) {
                    this.HasDisabledSupportField = value;
                    this.RaisePropertyChanged("HasDisabledSupport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDisabledWcSupport {
            get {
                return this.HasDisabledWcSupportField;
            }
            set {
                if ((this.HasDisabledWcSupportField.Equals(value) != true)) {
                    this.HasDisabledWcSupportField = value;
                    this.RaisePropertyChanged("HasDisabledWcSupport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSaladBar {
            get {
                return this.HasSaladBarField;
            }
            set {
                if ((this.HasSaladBarField.Equals(value) != true)) {
                    this.HasSaladBarField = value;
                    this.RaisePropertyChanged("HasSaladBar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasStudentBenefits {
            get {
                return this.HasStudentBenefitsField;
            }
            set {
                if ((this.HasStudentBenefitsField.Equals(value) != true)) {
                    this.HasStudentBenefitsField = value;
                    this.RaisePropertyChanged("HasStudentBenefits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasVegetarianSupport {
            get {
                return this.HasVegetarianSupportField;
            }
            set {
                if ((this.HasVegetarianSupportField.Equals(value) != true)) {
                    this.HasVegetarianSupportField = value;
                    this.RaisePropertyChanged("HasVegetarianSupport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OpenDuringWeekends {
            get {
                return this.OpenDuringWeekendsField;
            }
            set {
                if ((this.OpenDuringWeekendsField.Equals(value) != true)) {
                    this.OpenDuringWeekendsField = value;
                    this.RaisePropertyChanged("OpenDuringWeekends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BonRestApi.BonWs.OpeningTime OpeningTime {
            get {
                return this.OpeningTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.OpeningTimeField, value) != true)) {
                    this.OpeningTimeField = value;
                    this.RaisePropertyChanged("OpeningTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BonRestApi.BonWs.Price Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServesFastFood {
            get {
                return this.ServesFastFoodField;
            }
            set {
                if ((this.ServesFastFoodField.Equals(value) != true)) {
                    this.ServesFastFoodField = value;
                    this.RaisePropertyChanged("ServesFastFood");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServesLunch {
            get {
                return this.ServesLunchField;
            }
            set {
                if ((this.ServesLunchField.Equals(value) != true)) {
                    this.ServesLunchField = value;
                    this.RaisePropertyChanged("ServesLunch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServesPizzas {
            get {
                return this.ServesPizzasField;
            }
            set {
                if ((this.ServesPizzasField.Equals(value) != true)) {
                    this.ServesPizzasField = value;
                    this.RaisePropertyChanged("ServesPizzas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Price", Namespace="http://schemas.datacontract.org/2004/07/BonService")]
    [System.SerializableAttribute()]
    public partial class Price : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal From {
            get {
                return this.FromField;
            }
            set {
                if ((this.FromField.Equals(value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal To {
            get {
                return this.ToField;
            }
            set {
                if ((this.ToField.Equals(value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coordinates", Namespace="http://schemas.datacontract.org/2004/07/BonService")]
    [System.SerializableAttribute()]
    public partial class Coordinates : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RadiusKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RadiusKm {
            get {
                return this.RadiusKmField;
            }
            set {
                if ((this.RadiusKmField.Equals(value) != true)) {
                    this.RadiusKmField = value;
                    this.RaisePropertyChanged("RadiusKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BonWs.IBonService")]
    public interface IBonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBonService/GetAllRestaurants", ReplyAction="http://tempuri.org/IBonService/GetAllRestaurantsResponse")]
        BonRestApi.BonWs.Restaurants GetAllRestaurants();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBonService/GetAllRestaurants", ReplyAction="http://tempuri.org/IBonService/GetAllRestaurantsResponse")]
        System.Threading.Tasks.Task<BonRestApi.BonWs.Restaurants> GetAllRestaurantsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBonService/GetFilteredRestaurants", ReplyAction="http://tempuri.org/IBonService/GetFilteredRestaurantsResponse")]
        BonRestApi.BonWs.Restaurants GetFilteredRestaurants(BonRestApi.BonWs.Filter values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBonService/GetFilteredRestaurants", ReplyAction="http://tempuri.org/IBonService/GetFilteredRestaurantsResponse")]
        System.Threading.Tasks.Task<BonRestApi.BonWs.Restaurants> GetFilteredRestaurantsAsync(BonRestApi.BonWs.Filter values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBonService/GetCurrentlyOpenRestaurants", ReplyAction="http://tempuri.org/IBonService/GetCurrentlyOpenRestaurantsResponse")]
        BonRestApi.BonWs.Restaurants GetCurrentlyOpenRestaurants(System.DateTime now);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBonService/GetCurrentlyOpenRestaurants", ReplyAction="http://tempuri.org/IBonService/GetCurrentlyOpenRestaurantsResponse")]
        System.Threading.Tasks.Task<BonRestApi.BonWs.Restaurants> GetCurrentlyOpenRestaurantsAsync(System.DateTime now);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBonService/GetRestaurantsInRadius", ReplyAction="http://tempuri.org/IBonService/GetRestaurantsInRadiusResponse")]
        BonRestApi.BonWs.Restaurants GetRestaurantsInRadius(BonRestApi.BonWs.Coordinates value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBonService/GetRestaurantsInRadius", ReplyAction="http://tempuri.org/IBonService/GetRestaurantsInRadiusResponse")]
        System.Threading.Tasks.Task<BonRestApi.BonWs.Restaurants> GetRestaurantsInRadiusAsync(BonRestApi.BonWs.Coordinates value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBonService/ParseAllRestaurants", ReplyAction="http://tempuri.org/IBonService/ParseAllRestaurantsResponse")]
        void ParseAllRestaurants();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBonService/ParseAllRestaurants", ReplyAction="http://tempuri.org/IBonService/ParseAllRestaurantsResponse")]
        System.Threading.Tasks.Task ParseAllRestaurantsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBonServiceChannel : BonRestApi.BonWs.IBonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BonServiceClient : System.ServiceModel.ClientBase<BonRestApi.BonWs.IBonService>, BonRestApi.BonWs.IBonService {
        
        public BonServiceClient() {
        }
        
        public BonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BonRestApi.BonWs.Restaurants GetAllRestaurants() {
            return base.Channel.GetAllRestaurants();
        }
        
        public System.Threading.Tasks.Task<BonRestApi.BonWs.Restaurants> GetAllRestaurantsAsync() {
            return base.Channel.GetAllRestaurantsAsync();
        }
        
        public BonRestApi.BonWs.Restaurants GetFilteredRestaurants(BonRestApi.BonWs.Filter values) {
            return base.Channel.GetFilteredRestaurants(values);
        }
        
        public System.Threading.Tasks.Task<BonRestApi.BonWs.Restaurants> GetFilteredRestaurantsAsync(BonRestApi.BonWs.Filter values) {
            return base.Channel.GetFilteredRestaurantsAsync(values);
        }
        
        public BonRestApi.BonWs.Restaurants GetCurrentlyOpenRestaurants(System.DateTime now) {
            return base.Channel.GetCurrentlyOpenRestaurants(now);
        }
        
        public System.Threading.Tasks.Task<BonRestApi.BonWs.Restaurants> GetCurrentlyOpenRestaurantsAsync(System.DateTime now) {
            return base.Channel.GetCurrentlyOpenRestaurantsAsync(now);
        }
        
        public BonRestApi.BonWs.Restaurants GetRestaurantsInRadius(BonRestApi.BonWs.Coordinates value) {
            return base.Channel.GetRestaurantsInRadius(value);
        }
        
        public System.Threading.Tasks.Task<BonRestApi.BonWs.Restaurants> GetRestaurantsInRadiusAsync(BonRestApi.BonWs.Coordinates value) {
            return base.Channel.GetRestaurantsInRadiusAsync(value);
        }
        
        public void ParseAllRestaurants() {
            base.Channel.ParseAllRestaurants();
        }
        
        public System.Threading.Tasks.Task ParseAllRestaurantsAsync() {
            return base.Channel.ParseAllRestaurantsAsync();
        }
    }
}
